### PR TITLE
Build stylus-lang from source

### LINKED ISSUE #1: Build stylus-lang from source
I have successfully bundled [stylus/stylus#2394](https://github.com/stylus/stylus/pull/2394) to a single file. Here is the result:
https://github.com/eight04/stylus-lang-bundle/blob/dev-bundle/dist/stylus-renderer.min.js

Should I create a stylus-lang fork merged with [stylus/stylus#2394](https://github.com/stylus/stylus/pull/2394) and [stylus/stylus#2416](https://github.com/stylus/stylus/pull/2416) under `openstyles`?

And I will try to implement the bundle process in this repo.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #1.

* [x] Add test script.
* [x] Update readme.

If you want to try it out:
https://rawgit.com/eight04/stylus-lang-bundle-1/dev-rollup/demo/

### CODE REVIEW

**Comment by eight04** [comment]
@tophf @Mottie Can you test if you can produce the same dist? After cloning this branch, run:
```
npm install && npm run build && git diff
```

**Comment by tophf** [comment]
Yours has **a string** with `\r\n` inside, but mine has `\n` when I build from linux (cygwin/msys to be specific):

image

**Comment by Mottie** [comment]
No diff here on Windows 10.

**Comment by eight04** [comment]
The `\r` problem is fixed in https://github.com/openstyles/stylus-lang-bundle/pull/2/commits/26128b69164fa9f300d5e2c82633e0e5ee9d7534.

I think it is ready to merge.

**Comment by tophf** [comment]
I have no idea what all those impressive changes do, so I'll just ask this: is there a way to add all of the tests from the official stylus-lang repo? Just in case.

**Comment by eight04** [comment]
I added a test file that would run test cases of `stylus-lang` and fixed some issues. See also: https://github.com/openstyles/stylus-lang-bundle/issues/3.

**Comment by eight04** [comment]
All tests have passed.

**Comment by eight04** [comment]
@Mottie Can we merge this?

**Comment by Mottie** [comment]
Yeah, I completely forgot about it.

**Pull request merged**
