### PR TITLE
Bump stylus-lang to stylus/stylus#dev (v0.54.7)

### PR DESCRIPTION
**Pull request by eight04**
@Mottie @tophf BTW I have no write access to this repo.

### CODE REVIEW

**Comment by tophf** [comment]
Awesome!
One thing though, AMO doesn't allow to use untagged/dev/beta stuff - is it relevant?

**Comment by tophf** [comment]
@narcolepticinsomniac do you have write access in this repo to add eight04?

**Comment by eight04** [comment]
> AMO doesn't allow to use untagged/dev/beta stuff - is it relevant?

IDK. If we can't use the dev branch, we have to switch to the npm release and change the test case version accordingly:
https://github.com/openstyles/stylus-lang-bundle/blob/3da0291a5b7877179a3e0990072489c59e7b0f06/build-test-cases.mjs#L4

**Comment by tophf** [comment]
Mottie added you so now you can merge this yourself. As for AMO, I don't know if they check versions of the nested dependencies so maybe it's fine :-)

**Pull request merged**
